### ISSUE TITLE
Consistently crashes springboard on 14.1

### ISSUE THREAD

**Issue by lonkelle** [eclair4151/Push-For-Apollo#2]
The Shortlook Dev Team told me to contact you and give you this post in to help you diagnose and fix the problem:

https://pastebin.com/R3F8v275

**Comment by eclair4151** [comment]
The crash you have sent me is just a shortlook stack trace there isnt
really anything for me to do here.

My tweak is open source and only like 10 lines long. (it only reroutes the
notification to a different appID)
https://github.com/eclair4151/Push-For-Apollo/blob/master/Tweak.xm

Since the crash is on their end, and no one else has this problem im
not sure if there is anything I can do, except give you that and hope they
can help you.

Thanks!
Tomer

**Comment by lonkelle** [comment]
@eclair4151 I completely understand, I had to do what they asked first. I've know put the ball back in their court so I appreciate your quick response and VERY grateful for the great extension (even if it is only 10 lines of code 🙃).

**Comment by eclair4151** [comment]
To be clear though, i am sure this is due to the way I am forwarding the
notification and partially my fault. It is not the official way, so im sure
that is what is causing issues with the notifications. I don't know how to
do it correctly, so if they have a better suggestion on how I can correctly
forward notifications, i would be down to change if they can find out. i
tried for a while but couldn't find anything
Thanks!
Tomer

**Comment by lonkelle** [comment]
I sent them a link to this thread so if they care about Shortlook's dev community, and I'm sure they do. I have no doubt they'll respond here to you since I just send this issue link to their dev team. Crossing my fingers. 🤞
